title:  Stéphane Désiré Weya # your name (or website title) here
logo: "/images/PHOTO_DEZ.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  Bienvenue sur mes projets d'analyse de données 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
